<a href="https://colab.research.google.com/github/lovkush7/MACHINE-LEARNING-/blob/main/KNN%2CNB%2CDT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
path="/content/drive/MyDrive/disease_ml_dataset.csv"

In [4]:
import pandas as pd
df = pd.read_csv(path)

In [5]:
df.head()

,Age,Fever,Cough,Fatigue,Oxygen_Level,Heart_Rate,WBC_Count,Chest_Pain,Disease
0,25,0,0,0,98,72,18,No,No
1,30,0,0,1,99,75,20,No,No
2,35,1,0,0,98,78,22,No,No
3,40,1,0,1,97,82,24,Yes,No
4,45,1,1,0,96,85,26,Yes,Yes

In [6]:
df['Chest_Pain'] = df["Chest_Pain"].replace({
   "No": 0,
   "Yes": 1
})

/tmp/ipykernel_1109/3239762637.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Chest_Pain'] = df["Chest_Pain"].replace({

In [7]:
df['Disease'] = df['Disease'].replace({
    "Yes":1,
    "No": 0
})

/tmp/ipykernel_1109/1306188993.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Disease'] = df['Disease'].replace({

In [8]:
df.head()

,Age,Fever,Cough,Fatigue,Oxygen_Level,Heart_Rate,WBC_Count,Chest_Pain,Disease
0,25,0,0,0,98,72,18,0,0
1,30,0,0,1,99,75,20,0,0
2,35,1,0,0,98,78,22,0,0
3,40,1,0,1,97,82,24,1,0
4,45,1,1,0,96,85,26,1,1

In [9]:
x=df.drop("Disease",axis=1)
y=df["Disease"]

In [10]:
x

,Age,Fever,Cough,Fatigue,Oxygen_Level,Heart_Rate,WBC_Count,Chest_Pain
0,25,0,0,0,98,72,18,0
1,30,0,0,1,99,75,20,0
2,35,1,0,0,98,78,22,0
3,40,1,0,1,97,82,24,1
4,45,1,1,0,96,85,26,1
5,50,1,1,1,95,88,28,1
6,55,1,0,1,94,90,30,1
7,60,1,1,1,93,92,32,1
8,65,1,1,1,92,95,34,1
9,70,1,1,1,91,98,36,1
10,28,0,0,0,99,70,17,0
11,32,0,0,0,98,74,19,0
12,38,1,0,0,97,80,21,0
13,42,1,0,1,96,84,25,1
14,48,1,1,0,95,87,27,1
15,52,1,1,1,94,89,29,1
16,58,1,0,1,93,91,31,1
17,62,1,1,1,92,94,33,1
18,67,1,1,1,91,96,35,1
19,72,1,1,1,90,99,37,1
20,24,0,0,0,99,68,16,0
21,29,0,0,1,98,73,18,0
22,36,1,0,0,97,79,20,0
23,44,1,0,1,96,83,24,1
24,47,1,1,0,95,86,26,1
25,54,1,1,1,94,90,30,1
26,57,1,0,1,93,92,31,1
27,64,1,1,1,92,93,34,1
28,69,1,1,1,91,97,36,1
29,75,1,1,1,90,100,38,1

In [11]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [15]:
num_col=["Age","Oxygen_Level","Heart_Rate","WBC_Count"]
scaler = StandardScaler()

In [16]:
X_train[num_col] = scaler.fit_transform(X_train[num_col])
X_test[num_col] = scaler.transform(X_test[num_col])

In [18]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
)

In [19]:
KNN = KNeighborsClassifier(n_neighbors=5)
KNN.fit(X_train, y_train)

KNeighborsClassifier()

In [20]:
KNN_PRED = KNN.predict(X_test)

In [21]:
KNN_PRED

array([0, 1, 1, 1, 1, 0])

In [22]:
print("Actual:", y_test.values)
print("Predicted:", KNN_PRED)

Actual: [0 1 1 1 1 0]
Predicted: [0 1 1 1 1 0]

In [23]:
cn = confusion_matrix(y_test, KNN_PRED)
print(cn)

[[2 0]
 [0 4]]

In [24]:
accuracy = accuracy_score(y_test, KNN_PRED)
print(accuracy)

1.0

In [26]:
print(classification_report(y_test, KNN_PRED))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      1.00      1.00         4

    accuracy                           1.00         6
   macro avg       1.00      1.00      1.00         6
weighted avg       1.00      1.00      1.00         6

In [28]:
from sklearn.metrics import (


    precision_score,
    recall_score,
    f1_score,

)

In [29]:
print("Accuracy :", accuracy_score(y_test, KNN_PRED))
print("Precision:", precision_score(y_test, KNN_PRED))
print("Recall   :", recall_score(y_test, KNN_PRED))
print("F1 Score :", f1_score(y_test, KNN_PRED))

Accuracy : 1.0
Precision: 1.0
Recall   : 1.0
F1 Score : 1.0

In [31]:
from sklearn.naive_bayes import GaussianNB
NB = GaussianNB()
NB.fit(X_train, y_train)

GaussianNB()

In [32]:
NB_pred = NB.predict(X_test)

In [33]:
NB_pred

array([1, 1, 1, 1, 1, 0])

In [34]:
print("Actual:", y_test.values)
print("Predicted:", NB_pred)

Actual: [0 1 1 1 1 0]
Predicted: [1 1 1 1 1 0]

In [35]:
cn = confusion_matrix(y_test, NB_pred)
print(cn)

[[1 1]
 [0 4]]

In [36]:
print(classification_report(y_test, NB_pred))

              precision    recall  f1-score   support

           0       1.00      0.50      0.67         2
           1       0.80      1.00      0.89         4

    accuracy                           0.83         6
   macro avg       0.90      0.75      0.78         6
weighted avg       0.87      0.83      0.81         6

In [37]:
print("Accuracy :", accuracy_score(y_test, NB_pred))
print("Precision:", precision_score(y_test, NB_pred))
print("Recall   :", recall_score(y_test, NB_pred))
print("F1 Score :", f1_score(y_test, NB_pred))

Accuracy : 0.8333333333333334
Precision: 0.8
Recall   : 1.0
F1 Score : 0.8888888888888888

In [38]:
from sklearn.tree import DecisionTreeClassifier
DT = DecisionTreeClassifier()
DT.fit(X_train, y_train)

DecisionTreeClassifier()

In [40]:
DT_pred = DT.predict(X_test)
DT_pred

array([0, 1, 1, 1, 1, 0])

In [41]:
print("Actual:", y_test.values)
print("Predicted:", DT_pred)

Actual: [0 1 1 1 1 0]
Predicted: [0 1 1 1 1 0]

In [42]:
cn = confusion_matrix(y_test, DT_pred)
print(cn)

[[2 0]
 [0 4]]

In [43]:
print("Accuracy :", accuracy_score(y_test, DT_pred))
print("Precision:", precision_score(y_test, DT_pred))
print("Recall   :", recall_score(y_test, DT_pred))
print("F1 Score :", f1_score(y_test, DT_pred))

Accuracy : 1.0
Precision: 1.0
Recall   : 1.0
F1 Score : 1.0

In [44]:
knn_accuracy = accuracy_score(y_test, KNN_PRED)
nb_accuracy = accuracy_score(y_test, NB_pred)
dt_accuracy = accuracy_score(y_test, DT_pred)

print("KNN:", knn_accuracy)
print("Naive Bayes:", nb_accuracy)
print("Decision Tree:", dt_accuracy)

KNN: 1.0
Naive Bayes: 0.8333333333333334
Decision Tree: 1.0

In [45]:
results = pd.DataFrame({
    "Model": ["KNN", "Naive Bayes", "Decision Tree"],
    "Accuracy": [
        knn_accuracy,
        nb_accuracy,
        dt_accuracy
    ]
})

print(results)

           Model  Accuracy
0            KNN  1.000000
1    Naive Bayes  0.833333
2  Decision Tree  1.000000